# Makefile.in generated by automake 1.16.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2018 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/mines
pkgincludedir = $(includedir)/mines
pkglibdir = $(libdir)/mines
pkglibexecdir = $(libexecdir)/mines
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-apple-darwin18.0.0
host_triplet = x86_64-apple-darwin18.0.0
bin_PROGRAMS = mines$(EXEEXT)
am__append_1 = -F/Library/Frameworks -DGL_SILENCE_DEPRECATION
#am__append_2 = `pkg-config --cflags glew sdl2`
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am__dirstamp = $(am__leading_dot)dirstamp
am_mines_OBJECTS = src/mines-main.$(OBJEXT) \
	src/mines-gl_shader.$(OBJEXT) \
	src/mines-display_window.$(OBJEXT) \
	src/mines-mines_sys.$(OBJEXT) src/mines-nes_cpu.$(OBJEXT) \
	src/mines-nes_ppu.$(OBJEXT) src/mines-_nes_apu.$(OBJEXT) \
	src/mines-nes_cart.$(OBJEXT) \
	src/mines-nes_controllers.$(OBJEXT) \
	src/mines-ines_mapper.$(OBJEXT) \
	src/mines-ines_mapper0.$(OBJEXT) \
	src/mines-ines_mapper1.$(OBJEXT) \
	src/mines-ines_mapper2.$(OBJEXT) \
	src/mines-ines_mapper3.$(OBJEXT) \
	src/mines-ines_mapper7.$(OBJEXT) \
	src/Nes_Snd_Emu-0.1.7/mines-Sound_Queue.$(OBJEXT) \
	src/Nes_Snd_Emu-0.1.7/mines-Wave_Writer.$(OBJEXT) \
	src/Nes_Snd_Emu-0.1.7/nes_apu/mines-apu_snapshot.$(OBJEXT) \
	src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Blip_Buffer.$(OBJEXT) \
	src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Multi_Buffer.$(OBJEXT) \
	src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Apu.$(OBJEXT) \
	src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Namco.$(OBJEXT) \
	src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Oscs.$(OBJEXT) \
	src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Vrc6.$(OBJEXT) \
	src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nonlinear_Buffer.$(OBJEXT)
mines_OBJECTS = $(am_mines_OBJECTS)
mines_LDADD = $(LDADD)
mines_LINK = $(CXXLD) $(mines_CXXFLAGS) $(CXXFLAGS) $(mines_LDFLAGS) \
	$(LDFLAGS) -o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__maybe_remake_depfiles = depfiles
am__depfiles_remade = src/$(DEPDIR)/mines-_nes_apu.Po \
	src/$(DEPDIR)/mines-display_window.Po \
	src/$(DEPDIR)/mines-gl_shader.Po \
	src/$(DEPDIR)/mines-ines_mapper.Po \
	src/$(DEPDIR)/mines-ines_mapper0.Po \
	src/$(DEPDIR)/mines-ines_mapper1.Po \
	src/$(DEPDIR)/mines-ines_mapper2.Po \
	src/$(DEPDIR)/mines-ines_mapper3.Po \
	src/$(DEPDIR)/mines-ines_mapper7.Po \
	src/$(DEPDIR)/mines-main.Po src/$(DEPDIR)/mines-mines_sys.Po \
	src/$(DEPDIR)/mines-nes_cart.Po \
	src/$(DEPDIR)/mines-nes_controllers.Po \
	src/$(DEPDIR)/mines-nes_cpu.Po src/$(DEPDIR)/mines-nes_ppu.Po \
	src/Nes_Snd_Emu-0.1.7/$(DEPDIR)/mines-Sound_Queue.Po \
	src/Nes_Snd_Emu-0.1.7/$(DEPDIR)/mines-Wave_Writer.Po \
	src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Blip_Buffer.Po \
	src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Multi_Buffer.Po \
	src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Apu.Po \
	src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Namco.Po \
	src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Oscs.Po \
	src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Vrc6.Po \
	src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nonlinear_Buffer.Po \
	src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-apu_snapshot.Po
am__mv = mv -f
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX     " $@;
am__v_CXX_1 = 
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD   " $@;
am__v_CXXLD_1 = 
SOURCES = $(mines_SOURCES)
DIST_SOURCES = $(mines_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
am__DIST_COMMON = $(srcdir)/Makefile.in config.guess config.sub \
	depcomp install-sh missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /Users/ryan/src/miNES/missing aclocal-1.16
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AUTOCONF = ${SHELL} /Users/ryan/src/miNES/missing autoconf
AUTOHEADER = ${SHELL} /Users/ryan/src/miNES/missing autoheader
AUTOMAKE = ${SHELL} /Users/ryan/src/miNES/missing automake-1.16
AWK = awk
CPPFLAGS = 
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"mines\" -DPACKAGE_TARNAME=\"mines\" -DPACKAGE_VERSION=\"0.1\" -DPACKAGE_STRING=\"mines\ 0.1\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"mines\" -DVERSION=\"0.1\"
DEPDIR = .deps
ECHO_C = \c
ECHO_N = 
ECHO_T = 
EXEEXT = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /Users/ryan/src/miNES/missing makeinfo
MKDIR_P = ./install-sh -c -d
OBJEXT = o
PACKAGE = mines
PACKAGE_BUGREPORT = 
PACKAGE_NAME = mines
PACKAGE_STRING = mines 0.1
PACKAGE_TARNAME = mines
PACKAGE_URL = 
PACKAGE_VERSION = 0.1
PATH_SEPARATOR = :
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 0.1
abs_builddir = /Users/ryan/src/miNES
abs_srcdir = /Users/ryan/src/miNES
abs_top_builddir = /Users/ryan/src/miNES
abs_top_srcdir = /Users/ryan/src/miNES
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-apple-darwin18.0.0
build_alias = 
build_cpu = x86_64
build_os = darwin18.0.0
build_vendor = apple
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-apple-darwin18.0.0
host_alias = 
host_cpu = x86_64
host_os = darwin18.0.0
host_vendor = apple
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /Users/ryan/src/miNES/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = foreign
mines_SOURCES = \
    src/main.cpp \
    src/gl_shader.cpp \
    src/display_window.cpp \
    src/mines_sys.cpp \
    src/nes_cpu.cpp \
    src/nes_ppu.cpp \
    src/_nes_apu.cpp \
    src/nes_cart.cpp \
    src/nes_controllers.cpp \
    src/ines_mapper.cpp \
    src/ines_mapper0.cpp \
    src/ines_mapper1.cpp \
    src/ines_mapper2.cpp \
    src/ines_mapper3.cpp \
    src/ines_mapper7.cpp \
    src/Nes_Snd_Emu-0.1.7/Sound_Queue.cpp \
    src/Nes_Snd_Emu-0.1.7/Wave_Writer.cpp \
    src/Nes_Snd_Emu-0.1.7/nes_apu/apu_snapshot.cpp \
    src/Nes_Snd_Emu-0.1.7/nes_apu/Blip_Buffer.cpp \
    src/Nes_Snd_Emu-0.1.7/nes_apu/Multi_Buffer.cpp \
    src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Apu.cpp \
    src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Namco.cpp \
    src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Oscs.cpp \
    src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Vrc6.cpp \
    src/Nes_Snd_Emu-0.1.7/nes_apu/Nonlinear_Buffer.cpp

mines_CXXFLAGS = -Wall -Wno-c++11-narrowing -std=c++11 \
	-Isrc/Nes_Snd_Emu-0.1.7 $(am__append_1) $(am__append_2)
#mines_LDFLAGS = `pkg-config --libs glew sdl2`
mines_LDFLAGS = -framework OpenGL -framework SDL2
all: all-am

.SUFFIXES:
.SUFFIXES: .cpp .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
src/$(am__dirstamp):
	@$(MKDIR_P) src
	@: > src/$(am__dirstamp)
src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/$(DEPDIR)
	@: > src/$(DEPDIR)/$(am__dirstamp)
src/mines-main.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mines-gl_shader.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mines-display_window.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mines-mines_sys.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mines-nes_cpu.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mines-nes_ppu.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mines-_nes_apu.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mines-nes_cart.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mines-nes_controllers.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mines-ines_mapper.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mines-ines_mapper0.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mines-ines_mapper1.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mines-ines_mapper2.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mines-ines_mapper3.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mines-ines_mapper7.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/Nes_Snd_Emu-0.1.7/$(am__dirstamp):
	@$(MKDIR_P) src/Nes_Snd_Emu-0.1.7
	@: > src/Nes_Snd_Emu-0.1.7/$(am__dirstamp)
src/Nes_Snd_Emu-0.1.7/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/Nes_Snd_Emu-0.1.7/$(DEPDIR)
	@: > src/Nes_Snd_Emu-0.1.7/$(DEPDIR)/$(am__dirstamp)
src/Nes_Snd_Emu-0.1.7/mines-Sound_Queue.$(OBJEXT):  \
	src/Nes_Snd_Emu-0.1.7/$(am__dirstamp) \
	src/Nes_Snd_Emu-0.1.7/$(DEPDIR)/$(am__dirstamp)
src/Nes_Snd_Emu-0.1.7/mines-Wave_Writer.$(OBJEXT):  \
	src/Nes_Snd_Emu-0.1.7/$(am__dirstamp) \
	src/Nes_Snd_Emu-0.1.7/$(DEPDIR)/$(am__dirstamp)
src/Nes_Snd_Emu-0.1.7/nes_apu/$(am__dirstamp):
	@$(MKDIR_P) src/Nes_Snd_Emu-0.1.7/nes_apu
	@: > src/Nes_Snd_Emu-0.1.7/nes_apu/$(am__dirstamp)
src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)
	@: > src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/$(am__dirstamp)
src/Nes_Snd_Emu-0.1.7/nes_apu/mines-apu_snapshot.$(OBJEXT):  \
	src/Nes_Snd_Emu-0.1.7/nes_apu/$(am__dirstamp) \
	src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/$(am__dirstamp)
src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Blip_Buffer.$(OBJEXT):  \
	src/Nes_Snd_Emu-0.1.7/nes_apu/$(am__dirstamp) \
	src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/$(am__dirstamp)
src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Multi_Buffer.$(OBJEXT):  \
	src/Nes_Snd_Emu-0.1.7/nes_apu/$(am__dirstamp) \
	src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/$(am__dirstamp)
src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Apu.$(OBJEXT):  \
	src/Nes_Snd_Emu-0.1.7/nes_apu/$(am__dirstamp) \
	src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/$(am__dirstamp)
src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Namco.$(OBJEXT):  \
	src/Nes_Snd_Emu-0.1.7/nes_apu/$(am__dirstamp) \
	src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/$(am__dirstamp)
src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Oscs.$(OBJEXT):  \
	src/Nes_Snd_Emu-0.1.7/nes_apu/$(am__dirstamp) \
	src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/$(am__dirstamp)
src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Vrc6.$(OBJEXT):  \
	src/Nes_Snd_Emu-0.1.7/nes_apu/$(am__dirstamp) \
	src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/$(am__dirstamp)
src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nonlinear_Buffer.$(OBJEXT):  \
	src/Nes_Snd_Emu-0.1.7/nes_apu/$(am__dirstamp) \
	src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/$(am__dirstamp)

mines$(EXEEXT): $(mines_OBJECTS) $(mines_DEPENDENCIES) $(EXTRA_mines_DEPENDENCIES) 
	@rm -f mines$(EXEEXT)
	$(AM_V_CXXLD)$(mines_LINK) $(mines_OBJECTS) $(mines_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f src/*.$(OBJEXT)
	-rm -f src/Nes_Snd_Emu-0.1.7/*.$(OBJEXT)
	-rm -f src/Nes_Snd_Emu-0.1.7/nes_apu/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include src/$(DEPDIR)/mines-_nes_apu.Po # am--include-marker
include src/$(DEPDIR)/mines-display_window.Po # am--include-marker
include src/$(DEPDIR)/mines-gl_shader.Po # am--include-marker
include src/$(DEPDIR)/mines-ines_mapper.Po # am--include-marker
include src/$(DEPDIR)/mines-ines_mapper0.Po # am--include-marker
include src/$(DEPDIR)/mines-ines_mapper1.Po # am--include-marker
include src/$(DEPDIR)/mines-ines_mapper2.Po # am--include-marker
include src/$(DEPDIR)/mines-ines_mapper3.Po # am--include-marker
include src/$(DEPDIR)/mines-ines_mapper7.Po # am--include-marker
include src/$(DEPDIR)/mines-main.Po # am--include-marker
include src/$(DEPDIR)/mines-mines_sys.Po # am--include-marker
include src/$(DEPDIR)/mines-nes_cart.Po # am--include-marker
include src/$(DEPDIR)/mines-nes_controllers.Po # am--include-marker
include src/$(DEPDIR)/mines-nes_cpu.Po # am--include-marker
include src/$(DEPDIR)/mines-nes_ppu.Po # am--include-marker
include src/Nes_Snd_Emu-0.1.7/$(DEPDIR)/mines-Sound_Queue.Po # am--include-marker
include src/Nes_Snd_Emu-0.1.7/$(DEPDIR)/mines-Wave_Writer.Po # am--include-marker
include src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Blip_Buffer.Po # am--include-marker
include src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Multi_Buffer.Po # am--include-marker
include src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Apu.Po # am--include-marker
include src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Namco.Po # am--include-marker
include src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Oscs.Po # am--include-marker
include src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Vrc6.Po # am--include-marker
include src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nonlinear_Buffer.Po # am--include-marker
include src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-apu_snapshot.Po # am--include-marker

$(am__depfiles_remade):
	@$(MKDIR_P) $(@D)
	@echo '# dummy' >$@-t && $(am__mv) $@-t $@

am--depfiles: $(am__depfiles_remade)

.cpp.o:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

src/mines-main.o: src/main.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-main.o -MD -MP -MF src/$(DEPDIR)/mines-main.Tpo -c -o src/mines-main.o `test -f 'src/main.cpp' || echo '$(srcdir)/'`src/main.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-main.Tpo src/$(DEPDIR)/mines-main.Po
#	$(AM_V_CXX)source='src/main.cpp' object='src/mines-main.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-main.o `test -f 'src/main.cpp' || echo '$(srcdir)/'`src/main.cpp

src/mines-main.obj: src/main.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-main.obj -MD -MP -MF src/$(DEPDIR)/mines-main.Tpo -c -o src/mines-main.obj `if test -f 'src/main.cpp'; then $(CYGPATH_W) 'src/main.cpp'; else $(CYGPATH_W) '$(srcdir)/src/main.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-main.Tpo src/$(DEPDIR)/mines-main.Po
#	$(AM_V_CXX)source='src/main.cpp' object='src/mines-main.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-main.obj `if test -f 'src/main.cpp'; then $(CYGPATH_W) 'src/main.cpp'; else $(CYGPATH_W) '$(srcdir)/src/main.cpp'; fi`

src/mines-gl_shader.o: src/gl_shader.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-gl_shader.o -MD -MP -MF src/$(DEPDIR)/mines-gl_shader.Tpo -c -o src/mines-gl_shader.o `test -f 'src/gl_shader.cpp' || echo '$(srcdir)/'`src/gl_shader.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-gl_shader.Tpo src/$(DEPDIR)/mines-gl_shader.Po
#	$(AM_V_CXX)source='src/gl_shader.cpp' object='src/mines-gl_shader.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-gl_shader.o `test -f 'src/gl_shader.cpp' || echo '$(srcdir)/'`src/gl_shader.cpp

src/mines-gl_shader.obj: src/gl_shader.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-gl_shader.obj -MD -MP -MF src/$(DEPDIR)/mines-gl_shader.Tpo -c -o src/mines-gl_shader.obj `if test -f 'src/gl_shader.cpp'; then $(CYGPATH_W) 'src/gl_shader.cpp'; else $(CYGPATH_W) '$(srcdir)/src/gl_shader.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-gl_shader.Tpo src/$(DEPDIR)/mines-gl_shader.Po
#	$(AM_V_CXX)source='src/gl_shader.cpp' object='src/mines-gl_shader.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-gl_shader.obj `if test -f 'src/gl_shader.cpp'; then $(CYGPATH_W) 'src/gl_shader.cpp'; else $(CYGPATH_W) '$(srcdir)/src/gl_shader.cpp'; fi`

src/mines-display_window.o: src/display_window.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-display_window.o -MD -MP -MF src/$(DEPDIR)/mines-display_window.Tpo -c -o src/mines-display_window.o `test -f 'src/display_window.cpp' || echo '$(srcdir)/'`src/display_window.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-display_window.Tpo src/$(DEPDIR)/mines-display_window.Po
#	$(AM_V_CXX)source='src/display_window.cpp' object='src/mines-display_window.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-display_window.o `test -f 'src/display_window.cpp' || echo '$(srcdir)/'`src/display_window.cpp

src/mines-display_window.obj: src/display_window.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-display_window.obj -MD -MP -MF src/$(DEPDIR)/mines-display_window.Tpo -c -o src/mines-display_window.obj `if test -f 'src/display_window.cpp'; then $(CYGPATH_W) 'src/display_window.cpp'; else $(CYGPATH_W) '$(srcdir)/src/display_window.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-display_window.Tpo src/$(DEPDIR)/mines-display_window.Po
#	$(AM_V_CXX)source='src/display_window.cpp' object='src/mines-display_window.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-display_window.obj `if test -f 'src/display_window.cpp'; then $(CYGPATH_W) 'src/display_window.cpp'; else $(CYGPATH_W) '$(srcdir)/src/display_window.cpp'; fi`

src/mines-mines_sys.o: src/mines_sys.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-mines_sys.o -MD -MP -MF src/$(DEPDIR)/mines-mines_sys.Tpo -c -o src/mines-mines_sys.o `test -f 'src/mines_sys.cpp' || echo '$(srcdir)/'`src/mines_sys.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-mines_sys.Tpo src/$(DEPDIR)/mines-mines_sys.Po
#	$(AM_V_CXX)source='src/mines_sys.cpp' object='src/mines-mines_sys.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-mines_sys.o `test -f 'src/mines_sys.cpp' || echo '$(srcdir)/'`src/mines_sys.cpp

src/mines-mines_sys.obj: src/mines_sys.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-mines_sys.obj -MD -MP -MF src/$(DEPDIR)/mines-mines_sys.Tpo -c -o src/mines-mines_sys.obj `if test -f 'src/mines_sys.cpp'; then $(CYGPATH_W) 'src/mines_sys.cpp'; else $(CYGPATH_W) '$(srcdir)/src/mines_sys.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-mines_sys.Tpo src/$(DEPDIR)/mines-mines_sys.Po
#	$(AM_V_CXX)source='src/mines_sys.cpp' object='src/mines-mines_sys.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-mines_sys.obj `if test -f 'src/mines_sys.cpp'; then $(CYGPATH_W) 'src/mines_sys.cpp'; else $(CYGPATH_W) '$(srcdir)/src/mines_sys.cpp'; fi`

src/mines-nes_cpu.o: src/nes_cpu.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-nes_cpu.o -MD -MP -MF src/$(DEPDIR)/mines-nes_cpu.Tpo -c -o src/mines-nes_cpu.o `test -f 'src/nes_cpu.cpp' || echo '$(srcdir)/'`src/nes_cpu.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-nes_cpu.Tpo src/$(DEPDIR)/mines-nes_cpu.Po
#	$(AM_V_CXX)source='src/nes_cpu.cpp' object='src/mines-nes_cpu.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-nes_cpu.o `test -f 'src/nes_cpu.cpp' || echo '$(srcdir)/'`src/nes_cpu.cpp

src/mines-nes_cpu.obj: src/nes_cpu.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-nes_cpu.obj -MD -MP -MF src/$(DEPDIR)/mines-nes_cpu.Tpo -c -o src/mines-nes_cpu.obj `if test -f 'src/nes_cpu.cpp'; then $(CYGPATH_W) 'src/nes_cpu.cpp'; else $(CYGPATH_W) '$(srcdir)/src/nes_cpu.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-nes_cpu.Tpo src/$(DEPDIR)/mines-nes_cpu.Po
#	$(AM_V_CXX)source='src/nes_cpu.cpp' object='src/mines-nes_cpu.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-nes_cpu.obj `if test -f 'src/nes_cpu.cpp'; then $(CYGPATH_W) 'src/nes_cpu.cpp'; else $(CYGPATH_W) '$(srcdir)/src/nes_cpu.cpp'; fi`

src/mines-nes_ppu.o: src/nes_ppu.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-nes_ppu.o -MD -MP -MF src/$(DEPDIR)/mines-nes_ppu.Tpo -c -o src/mines-nes_ppu.o `test -f 'src/nes_ppu.cpp' || echo '$(srcdir)/'`src/nes_ppu.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-nes_ppu.Tpo src/$(DEPDIR)/mines-nes_ppu.Po
#	$(AM_V_CXX)source='src/nes_ppu.cpp' object='src/mines-nes_ppu.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-nes_ppu.o `test -f 'src/nes_ppu.cpp' || echo '$(srcdir)/'`src/nes_ppu.cpp

src/mines-nes_ppu.obj: src/nes_ppu.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-nes_ppu.obj -MD -MP -MF src/$(DEPDIR)/mines-nes_ppu.Tpo -c -o src/mines-nes_ppu.obj `if test -f 'src/nes_ppu.cpp'; then $(CYGPATH_W) 'src/nes_ppu.cpp'; else $(CYGPATH_W) '$(srcdir)/src/nes_ppu.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-nes_ppu.Tpo src/$(DEPDIR)/mines-nes_ppu.Po
#	$(AM_V_CXX)source='src/nes_ppu.cpp' object='src/mines-nes_ppu.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-nes_ppu.obj `if test -f 'src/nes_ppu.cpp'; then $(CYGPATH_W) 'src/nes_ppu.cpp'; else $(CYGPATH_W) '$(srcdir)/src/nes_ppu.cpp'; fi`

src/mines-_nes_apu.o: src/_nes_apu.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-_nes_apu.o -MD -MP -MF src/$(DEPDIR)/mines-_nes_apu.Tpo -c -o src/mines-_nes_apu.o `test -f 'src/_nes_apu.cpp' || echo '$(srcdir)/'`src/_nes_apu.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-_nes_apu.Tpo src/$(DEPDIR)/mines-_nes_apu.Po
#	$(AM_V_CXX)source='src/_nes_apu.cpp' object='src/mines-_nes_apu.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-_nes_apu.o `test -f 'src/_nes_apu.cpp' || echo '$(srcdir)/'`src/_nes_apu.cpp

src/mines-_nes_apu.obj: src/_nes_apu.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-_nes_apu.obj -MD -MP -MF src/$(DEPDIR)/mines-_nes_apu.Tpo -c -o src/mines-_nes_apu.obj `if test -f 'src/_nes_apu.cpp'; then $(CYGPATH_W) 'src/_nes_apu.cpp'; else $(CYGPATH_W) '$(srcdir)/src/_nes_apu.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-_nes_apu.Tpo src/$(DEPDIR)/mines-_nes_apu.Po
#	$(AM_V_CXX)source='src/_nes_apu.cpp' object='src/mines-_nes_apu.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-_nes_apu.obj `if test -f 'src/_nes_apu.cpp'; then $(CYGPATH_W) 'src/_nes_apu.cpp'; else $(CYGPATH_W) '$(srcdir)/src/_nes_apu.cpp'; fi`

src/mines-nes_cart.o: src/nes_cart.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-nes_cart.o -MD -MP -MF src/$(DEPDIR)/mines-nes_cart.Tpo -c -o src/mines-nes_cart.o `test -f 'src/nes_cart.cpp' || echo '$(srcdir)/'`src/nes_cart.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-nes_cart.Tpo src/$(DEPDIR)/mines-nes_cart.Po
#	$(AM_V_CXX)source='src/nes_cart.cpp' object='src/mines-nes_cart.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-nes_cart.o `test -f 'src/nes_cart.cpp' || echo '$(srcdir)/'`src/nes_cart.cpp

src/mines-nes_cart.obj: src/nes_cart.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-nes_cart.obj -MD -MP -MF src/$(DEPDIR)/mines-nes_cart.Tpo -c -o src/mines-nes_cart.obj `if test -f 'src/nes_cart.cpp'; then $(CYGPATH_W) 'src/nes_cart.cpp'; else $(CYGPATH_W) '$(srcdir)/src/nes_cart.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-nes_cart.Tpo src/$(DEPDIR)/mines-nes_cart.Po
#	$(AM_V_CXX)source='src/nes_cart.cpp' object='src/mines-nes_cart.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-nes_cart.obj `if test -f 'src/nes_cart.cpp'; then $(CYGPATH_W) 'src/nes_cart.cpp'; else $(CYGPATH_W) '$(srcdir)/src/nes_cart.cpp'; fi`

src/mines-nes_controllers.o: src/nes_controllers.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-nes_controllers.o -MD -MP -MF src/$(DEPDIR)/mines-nes_controllers.Tpo -c -o src/mines-nes_controllers.o `test -f 'src/nes_controllers.cpp' || echo '$(srcdir)/'`src/nes_controllers.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-nes_controllers.Tpo src/$(DEPDIR)/mines-nes_controllers.Po
#	$(AM_V_CXX)source='src/nes_controllers.cpp' object='src/mines-nes_controllers.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-nes_controllers.o `test -f 'src/nes_controllers.cpp' || echo '$(srcdir)/'`src/nes_controllers.cpp

src/mines-nes_controllers.obj: src/nes_controllers.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-nes_controllers.obj -MD -MP -MF src/$(DEPDIR)/mines-nes_controllers.Tpo -c -o src/mines-nes_controllers.obj `if test -f 'src/nes_controllers.cpp'; then $(CYGPATH_W) 'src/nes_controllers.cpp'; else $(CYGPATH_W) '$(srcdir)/src/nes_controllers.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-nes_controllers.Tpo src/$(DEPDIR)/mines-nes_controllers.Po
#	$(AM_V_CXX)source='src/nes_controllers.cpp' object='src/mines-nes_controllers.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-nes_controllers.obj `if test -f 'src/nes_controllers.cpp'; then $(CYGPATH_W) 'src/nes_controllers.cpp'; else $(CYGPATH_W) '$(srcdir)/src/nes_controllers.cpp'; fi`

src/mines-ines_mapper.o: src/ines_mapper.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-ines_mapper.o -MD -MP -MF src/$(DEPDIR)/mines-ines_mapper.Tpo -c -o src/mines-ines_mapper.o `test -f 'src/ines_mapper.cpp' || echo '$(srcdir)/'`src/ines_mapper.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-ines_mapper.Tpo src/$(DEPDIR)/mines-ines_mapper.Po
#	$(AM_V_CXX)source='src/ines_mapper.cpp' object='src/mines-ines_mapper.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-ines_mapper.o `test -f 'src/ines_mapper.cpp' || echo '$(srcdir)/'`src/ines_mapper.cpp

src/mines-ines_mapper.obj: src/ines_mapper.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-ines_mapper.obj -MD -MP -MF src/$(DEPDIR)/mines-ines_mapper.Tpo -c -o src/mines-ines_mapper.obj `if test -f 'src/ines_mapper.cpp'; then $(CYGPATH_W) 'src/ines_mapper.cpp'; else $(CYGPATH_W) '$(srcdir)/src/ines_mapper.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-ines_mapper.Tpo src/$(DEPDIR)/mines-ines_mapper.Po
#	$(AM_V_CXX)source='src/ines_mapper.cpp' object='src/mines-ines_mapper.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-ines_mapper.obj `if test -f 'src/ines_mapper.cpp'; then $(CYGPATH_W) 'src/ines_mapper.cpp'; else $(CYGPATH_W) '$(srcdir)/src/ines_mapper.cpp'; fi`

src/mines-ines_mapper0.o: src/ines_mapper0.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-ines_mapper0.o -MD -MP -MF src/$(DEPDIR)/mines-ines_mapper0.Tpo -c -o src/mines-ines_mapper0.o `test -f 'src/ines_mapper0.cpp' || echo '$(srcdir)/'`src/ines_mapper0.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-ines_mapper0.Tpo src/$(DEPDIR)/mines-ines_mapper0.Po
#	$(AM_V_CXX)source='src/ines_mapper0.cpp' object='src/mines-ines_mapper0.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-ines_mapper0.o `test -f 'src/ines_mapper0.cpp' || echo '$(srcdir)/'`src/ines_mapper0.cpp

src/mines-ines_mapper0.obj: src/ines_mapper0.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-ines_mapper0.obj -MD -MP -MF src/$(DEPDIR)/mines-ines_mapper0.Tpo -c -o src/mines-ines_mapper0.obj `if test -f 'src/ines_mapper0.cpp'; then $(CYGPATH_W) 'src/ines_mapper0.cpp'; else $(CYGPATH_W) '$(srcdir)/src/ines_mapper0.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-ines_mapper0.Tpo src/$(DEPDIR)/mines-ines_mapper0.Po
#	$(AM_V_CXX)source='src/ines_mapper0.cpp' object='src/mines-ines_mapper0.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-ines_mapper0.obj `if test -f 'src/ines_mapper0.cpp'; then $(CYGPATH_W) 'src/ines_mapper0.cpp'; else $(CYGPATH_W) '$(srcdir)/src/ines_mapper0.cpp'; fi`

src/mines-ines_mapper1.o: src/ines_mapper1.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-ines_mapper1.o -MD -MP -MF src/$(DEPDIR)/mines-ines_mapper1.Tpo -c -o src/mines-ines_mapper1.o `test -f 'src/ines_mapper1.cpp' || echo '$(srcdir)/'`src/ines_mapper1.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-ines_mapper1.Tpo src/$(DEPDIR)/mines-ines_mapper1.Po
#	$(AM_V_CXX)source='src/ines_mapper1.cpp' object='src/mines-ines_mapper1.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-ines_mapper1.o `test -f 'src/ines_mapper1.cpp' || echo '$(srcdir)/'`src/ines_mapper1.cpp

src/mines-ines_mapper1.obj: src/ines_mapper1.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-ines_mapper1.obj -MD -MP -MF src/$(DEPDIR)/mines-ines_mapper1.Tpo -c -o src/mines-ines_mapper1.obj `if test -f 'src/ines_mapper1.cpp'; then $(CYGPATH_W) 'src/ines_mapper1.cpp'; else $(CYGPATH_W) '$(srcdir)/src/ines_mapper1.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-ines_mapper1.Tpo src/$(DEPDIR)/mines-ines_mapper1.Po
#	$(AM_V_CXX)source='src/ines_mapper1.cpp' object='src/mines-ines_mapper1.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-ines_mapper1.obj `if test -f 'src/ines_mapper1.cpp'; then $(CYGPATH_W) 'src/ines_mapper1.cpp'; else $(CYGPATH_W) '$(srcdir)/src/ines_mapper1.cpp'; fi`

src/mines-ines_mapper2.o: src/ines_mapper2.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-ines_mapper2.o -MD -MP -MF src/$(DEPDIR)/mines-ines_mapper2.Tpo -c -o src/mines-ines_mapper2.o `test -f 'src/ines_mapper2.cpp' || echo '$(srcdir)/'`src/ines_mapper2.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-ines_mapper2.Tpo src/$(DEPDIR)/mines-ines_mapper2.Po
#	$(AM_V_CXX)source='src/ines_mapper2.cpp' object='src/mines-ines_mapper2.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-ines_mapper2.o `test -f 'src/ines_mapper2.cpp' || echo '$(srcdir)/'`src/ines_mapper2.cpp

src/mines-ines_mapper2.obj: src/ines_mapper2.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-ines_mapper2.obj -MD -MP -MF src/$(DEPDIR)/mines-ines_mapper2.Tpo -c -o src/mines-ines_mapper2.obj `if test -f 'src/ines_mapper2.cpp'; then $(CYGPATH_W) 'src/ines_mapper2.cpp'; else $(CYGPATH_W) '$(srcdir)/src/ines_mapper2.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-ines_mapper2.Tpo src/$(DEPDIR)/mines-ines_mapper2.Po
#	$(AM_V_CXX)source='src/ines_mapper2.cpp' object='src/mines-ines_mapper2.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-ines_mapper2.obj `if test -f 'src/ines_mapper2.cpp'; then $(CYGPATH_W) 'src/ines_mapper2.cpp'; else $(CYGPATH_W) '$(srcdir)/src/ines_mapper2.cpp'; fi`

src/mines-ines_mapper3.o: src/ines_mapper3.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-ines_mapper3.o -MD -MP -MF src/$(DEPDIR)/mines-ines_mapper3.Tpo -c -o src/mines-ines_mapper3.o `test -f 'src/ines_mapper3.cpp' || echo '$(srcdir)/'`src/ines_mapper3.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-ines_mapper3.Tpo src/$(DEPDIR)/mines-ines_mapper3.Po
#	$(AM_V_CXX)source='src/ines_mapper3.cpp' object='src/mines-ines_mapper3.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-ines_mapper3.o `test -f 'src/ines_mapper3.cpp' || echo '$(srcdir)/'`src/ines_mapper3.cpp

src/mines-ines_mapper3.obj: src/ines_mapper3.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-ines_mapper3.obj -MD -MP -MF src/$(DEPDIR)/mines-ines_mapper3.Tpo -c -o src/mines-ines_mapper3.obj `if test -f 'src/ines_mapper3.cpp'; then $(CYGPATH_W) 'src/ines_mapper3.cpp'; else $(CYGPATH_W) '$(srcdir)/src/ines_mapper3.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-ines_mapper3.Tpo src/$(DEPDIR)/mines-ines_mapper3.Po
#	$(AM_V_CXX)source='src/ines_mapper3.cpp' object='src/mines-ines_mapper3.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-ines_mapper3.obj `if test -f 'src/ines_mapper3.cpp'; then $(CYGPATH_W) 'src/ines_mapper3.cpp'; else $(CYGPATH_W) '$(srcdir)/src/ines_mapper3.cpp'; fi`

src/mines-ines_mapper7.o: src/ines_mapper7.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-ines_mapper7.o -MD -MP -MF src/$(DEPDIR)/mines-ines_mapper7.Tpo -c -o src/mines-ines_mapper7.o `test -f 'src/ines_mapper7.cpp' || echo '$(srcdir)/'`src/ines_mapper7.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-ines_mapper7.Tpo src/$(DEPDIR)/mines-ines_mapper7.Po
#	$(AM_V_CXX)source='src/ines_mapper7.cpp' object='src/mines-ines_mapper7.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-ines_mapper7.o `test -f 'src/ines_mapper7.cpp' || echo '$(srcdir)/'`src/ines_mapper7.cpp

src/mines-ines_mapper7.obj: src/ines_mapper7.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/mines-ines_mapper7.obj -MD -MP -MF src/$(DEPDIR)/mines-ines_mapper7.Tpo -c -o src/mines-ines_mapper7.obj `if test -f 'src/ines_mapper7.cpp'; then $(CYGPATH_W) 'src/ines_mapper7.cpp'; else $(CYGPATH_W) '$(srcdir)/src/ines_mapper7.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mines-ines_mapper7.Tpo src/$(DEPDIR)/mines-ines_mapper7.Po
#	$(AM_V_CXX)source='src/ines_mapper7.cpp' object='src/mines-ines_mapper7.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/mines-ines_mapper7.obj `if test -f 'src/ines_mapper7.cpp'; then $(CYGPATH_W) 'src/ines_mapper7.cpp'; else $(CYGPATH_W) '$(srcdir)/src/ines_mapper7.cpp'; fi`

src/Nes_Snd_Emu-0.1.7/mines-Sound_Queue.o: src/Nes_Snd_Emu-0.1.7/Sound_Queue.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/Nes_Snd_Emu-0.1.7/mines-Sound_Queue.o -MD -MP -MF src/Nes_Snd_Emu-0.1.7/$(DEPDIR)/mines-Sound_Queue.Tpo -c -o src/Nes_Snd_Emu-0.1.7/mines-Sound_Queue.o `test -f 'src/Nes_Snd_Emu-0.1.7/Sound_Queue.cpp' || echo '$(srcdir)/'`src/Nes_Snd_Emu-0.1.7/Sound_Queue.cpp
	$(AM_V_at)$(am__mv) src/Nes_Snd_Emu-0.1.7/$(DEPDIR)/mines-Sound_Queue.Tpo src/Nes_Snd_Emu-0.1.7/$(DEPDIR)/mines-Sound_Queue.Po
#	$(AM_V_CXX)source='src/Nes_Snd_Emu-0.1.7/Sound_Queue.cpp' object='src/Nes_Snd_Emu-0.1.7/mines-Sound_Queue.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/Nes_Snd_Emu-0.1.7/mines-Sound_Queue.o `test -f 'src/Nes_Snd_Emu-0.1.7/Sound_Queue.cpp' || echo '$(srcdir)/'`src/Nes_Snd_Emu-0.1.7/Sound_Queue.cpp

src/Nes_Snd_Emu-0.1.7/mines-Sound_Queue.obj: src/Nes_Snd_Emu-0.1.7/Sound_Queue.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/Nes_Snd_Emu-0.1.7/mines-Sound_Queue.obj -MD -MP -MF src/Nes_Snd_Emu-0.1.7/$(DEPDIR)/mines-Sound_Queue.Tpo -c -o src/Nes_Snd_Emu-0.1.7/mines-Sound_Queue.obj `if test -f 'src/Nes_Snd_Emu-0.1.7/Sound_Queue.cpp'; then $(CYGPATH_W) 'src/Nes_Snd_Emu-0.1.7/Sound_Queue.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Nes_Snd_Emu-0.1.7/Sound_Queue.cpp'; fi`
	$(AM_V_at)$(am__mv) src/Nes_Snd_Emu-0.1.7/$(DEPDIR)/mines-Sound_Queue.Tpo src/Nes_Snd_Emu-0.1.7/$(DEPDIR)/mines-Sound_Queue.Po
#	$(AM_V_CXX)source='src/Nes_Snd_Emu-0.1.7/Sound_Queue.cpp' object='src/Nes_Snd_Emu-0.1.7/mines-Sound_Queue.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/Nes_Snd_Emu-0.1.7/mines-Sound_Queue.obj `if test -f 'src/Nes_Snd_Emu-0.1.7/Sound_Queue.cpp'; then $(CYGPATH_W) 'src/Nes_Snd_Emu-0.1.7/Sound_Queue.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Nes_Snd_Emu-0.1.7/Sound_Queue.cpp'; fi`

src/Nes_Snd_Emu-0.1.7/mines-Wave_Writer.o: src/Nes_Snd_Emu-0.1.7/Wave_Writer.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/Nes_Snd_Emu-0.1.7/mines-Wave_Writer.o -MD -MP -MF src/Nes_Snd_Emu-0.1.7/$(DEPDIR)/mines-Wave_Writer.Tpo -c -o src/Nes_Snd_Emu-0.1.7/mines-Wave_Writer.o `test -f 'src/Nes_Snd_Emu-0.1.7/Wave_Writer.cpp' || echo '$(srcdir)/'`src/Nes_Snd_Emu-0.1.7/Wave_Writer.cpp
	$(AM_V_at)$(am__mv) src/Nes_Snd_Emu-0.1.7/$(DEPDIR)/mines-Wave_Writer.Tpo src/Nes_Snd_Emu-0.1.7/$(DEPDIR)/mines-Wave_Writer.Po
#	$(AM_V_CXX)source='src/Nes_Snd_Emu-0.1.7/Wave_Writer.cpp' object='src/Nes_Snd_Emu-0.1.7/mines-Wave_Writer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/Nes_Snd_Emu-0.1.7/mines-Wave_Writer.o `test -f 'src/Nes_Snd_Emu-0.1.7/Wave_Writer.cpp' || echo '$(srcdir)/'`src/Nes_Snd_Emu-0.1.7/Wave_Writer.cpp

src/Nes_Snd_Emu-0.1.7/mines-Wave_Writer.obj: src/Nes_Snd_Emu-0.1.7/Wave_Writer.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/Nes_Snd_Emu-0.1.7/mines-Wave_Writer.obj -MD -MP -MF src/Nes_Snd_Emu-0.1.7/$(DEPDIR)/mines-Wave_Writer.Tpo -c -o src/Nes_Snd_Emu-0.1.7/mines-Wave_Writer.obj `if test -f 'src/Nes_Snd_Emu-0.1.7/Wave_Writer.cpp'; then $(CYGPATH_W) 'src/Nes_Snd_Emu-0.1.7/Wave_Writer.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Nes_Snd_Emu-0.1.7/Wave_Writer.cpp'; fi`
	$(AM_V_at)$(am__mv) src/Nes_Snd_Emu-0.1.7/$(DEPDIR)/mines-Wave_Writer.Tpo src/Nes_Snd_Emu-0.1.7/$(DEPDIR)/mines-Wave_Writer.Po
#	$(AM_V_CXX)source='src/Nes_Snd_Emu-0.1.7/Wave_Writer.cpp' object='src/Nes_Snd_Emu-0.1.7/mines-Wave_Writer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/Nes_Snd_Emu-0.1.7/mines-Wave_Writer.obj `if test -f 'src/Nes_Snd_Emu-0.1.7/Wave_Writer.cpp'; then $(CYGPATH_W) 'src/Nes_Snd_Emu-0.1.7/Wave_Writer.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Nes_Snd_Emu-0.1.7/Wave_Writer.cpp'; fi`

src/Nes_Snd_Emu-0.1.7/nes_apu/mines-apu_snapshot.o: src/Nes_Snd_Emu-0.1.7/nes_apu/apu_snapshot.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/Nes_Snd_Emu-0.1.7/nes_apu/mines-apu_snapshot.o -MD -MP -MF src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-apu_snapshot.Tpo -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-apu_snapshot.o `test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/apu_snapshot.cpp' || echo '$(srcdir)/'`src/Nes_Snd_Emu-0.1.7/nes_apu/apu_snapshot.cpp
	$(AM_V_at)$(am__mv) src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-apu_snapshot.Tpo src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-apu_snapshot.Po
#	$(AM_V_CXX)source='src/Nes_Snd_Emu-0.1.7/nes_apu/apu_snapshot.cpp' object='src/Nes_Snd_Emu-0.1.7/nes_apu/mines-apu_snapshot.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-apu_snapshot.o `test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/apu_snapshot.cpp' || echo '$(srcdir)/'`src/Nes_Snd_Emu-0.1.7/nes_apu/apu_snapshot.cpp

src/Nes_Snd_Emu-0.1.7/nes_apu/mines-apu_snapshot.obj: src/Nes_Snd_Emu-0.1.7/nes_apu/apu_snapshot.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/Nes_Snd_Emu-0.1.7/nes_apu/mines-apu_snapshot.obj -MD -MP -MF src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-apu_snapshot.Tpo -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-apu_snapshot.obj `if test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/apu_snapshot.cpp'; then $(CYGPATH_W) 'src/Nes_Snd_Emu-0.1.7/nes_apu/apu_snapshot.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Nes_Snd_Emu-0.1.7/nes_apu/apu_snapshot.cpp'; fi`
	$(AM_V_at)$(am__mv) src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-apu_snapshot.Tpo src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-apu_snapshot.Po
#	$(AM_V_CXX)source='src/Nes_Snd_Emu-0.1.7/nes_apu/apu_snapshot.cpp' object='src/Nes_Snd_Emu-0.1.7/nes_apu/mines-apu_snapshot.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-apu_snapshot.obj `if test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/apu_snapshot.cpp'; then $(CYGPATH_W) 'src/Nes_Snd_Emu-0.1.7/nes_apu/apu_snapshot.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Nes_Snd_Emu-0.1.7/nes_apu/apu_snapshot.cpp'; fi`

src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Blip_Buffer.o: src/Nes_Snd_Emu-0.1.7/nes_apu/Blip_Buffer.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Blip_Buffer.o -MD -MP -MF src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Blip_Buffer.Tpo -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Blip_Buffer.o `test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Blip_Buffer.cpp' || echo '$(srcdir)/'`src/Nes_Snd_Emu-0.1.7/nes_apu/Blip_Buffer.cpp
	$(AM_V_at)$(am__mv) src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Blip_Buffer.Tpo src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Blip_Buffer.Po
#	$(AM_V_CXX)source='src/Nes_Snd_Emu-0.1.7/nes_apu/Blip_Buffer.cpp' object='src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Blip_Buffer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Blip_Buffer.o `test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Blip_Buffer.cpp' || echo '$(srcdir)/'`src/Nes_Snd_Emu-0.1.7/nes_apu/Blip_Buffer.cpp

src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Blip_Buffer.obj: src/Nes_Snd_Emu-0.1.7/nes_apu/Blip_Buffer.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Blip_Buffer.obj -MD -MP -MF src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Blip_Buffer.Tpo -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Blip_Buffer.obj `if test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Blip_Buffer.cpp'; then $(CYGPATH_W) 'src/Nes_Snd_Emu-0.1.7/nes_apu/Blip_Buffer.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Nes_Snd_Emu-0.1.7/nes_apu/Blip_Buffer.cpp'; fi`
	$(AM_V_at)$(am__mv) src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Blip_Buffer.Tpo src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Blip_Buffer.Po
#	$(AM_V_CXX)source='src/Nes_Snd_Emu-0.1.7/nes_apu/Blip_Buffer.cpp' object='src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Blip_Buffer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Blip_Buffer.obj `if test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Blip_Buffer.cpp'; then $(CYGPATH_W) 'src/Nes_Snd_Emu-0.1.7/nes_apu/Blip_Buffer.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Nes_Snd_Emu-0.1.7/nes_apu/Blip_Buffer.cpp'; fi`

src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Multi_Buffer.o: src/Nes_Snd_Emu-0.1.7/nes_apu/Multi_Buffer.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Multi_Buffer.o -MD -MP -MF src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Multi_Buffer.Tpo -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Multi_Buffer.o `test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Multi_Buffer.cpp' || echo '$(srcdir)/'`src/Nes_Snd_Emu-0.1.7/nes_apu/Multi_Buffer.cpp
	$(AM_V_at)$(am__mv) src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Multi_Buffer.Tpo src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Multi_Buffer.Po
#	$(AM_V_CXX)source='src/Nes_Snd_Emu-0.1.7/nes_apu/Multi_Buffer.cpp' object='src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Multi_Buffer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Multi_Buffer.o `test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Multi_Buffer.cpp' || echo '$(srcdir)/'`src/Nes_Snd_Emu-0.1.7/nes_apu/Multi_Buffer.cpp

src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Multi_Buffer.obj: src/Nes_Snd_Emu-0.1.7/nes_apu/Multi_Buffer.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Multi_Buffer.obj -MD -MP -MF src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Multi_Buffer.Tpo -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Multi_Buffer.obj `if test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Multi_Buffer.cpp'; then $(CYGPATH_W) 'src/Nes_Snd_Emu-0.1.7/nes_apu/Multi_Buffer.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Nes_Snd_Emu-0.1.7/nes_apu/Multi_Buffer.cpp'; fi`
	$(AM_V_at)$(am__mv) src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Multi_Buffer.Tpo src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Multi_Buffer.Po
#	$(AM_V_CXX)source='src/Nes_Snd_Emu-0.1.7/nes_apu/Multi_Buffer.cpp' object='src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Multi_Buffer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Multi_Buffer.obj `if test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Multi_Buffer.cpp'; then $(CYGPATH_W) 'src/Nes_Snd_Emu-0.1.7/nes_apu/Multi_Buffer.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Nes_Snd_Emu-0.1.7/nes_apu/Multi_Buffer.cpp'; fi`

src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Apu.o: src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Apu.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Apu.o -MD -MP -MF src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Apu.Tpo -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Apu.o `test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Apu.cpp' || echo '$(srcdir)/'`src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Apu.cpp
	$(AM_V_at)$(am__mv) src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Apu.Tpo src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Apu.Po
#	$(AM_V_CXX)source='src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Apu.cpp' object='src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Apu.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Apu.o `test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Apu.cpp' || echo '$(srcdir)/'`src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Apu.cpp

src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Apu.obj: src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Apu.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Apu.obj -MD -MP -MF src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Apu.Tpo -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Apu.obj `if test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Apu.cpp'; then $(CYGPATH_W) 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Apu.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Apu.cpp'; fi`
	$(AM_V_at)$(am__mv) src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Apu.Tpo src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Apu.Po
#	$(AM_V_CXX)source='src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Apu.cpp' object='src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Apu.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Apu.obj `if test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Apu.cpp'; then $(CYGPATH_W) 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Apu.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Apu.cpp'; fi`

src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Namco.o: src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Namco.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Namco.o -MD -MP -MF src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Namco.Tpo -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Namco.o `test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Namco.cpp' || echo '$(srcdir)/'`src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Namco.cpp
	$(AM_V_at)$(am__mv) src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Namco.Tpo src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Namco.Po
#	$(AM_V_CXX)source='src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Namco.cpp' object='src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Namco.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Namco.o `test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Namco.cpp' || echo '$(srcdir)/'`src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Namco.cpp

src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Namco.obj: src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Namco.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Namco.obj -MD -MP -MF src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Namco.Tpo -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Namco.obj `if test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Namco.cpp'; then $(CYGPATH_W) 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Namco.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Namco.cpp'; fi`
	$(AM_V_at)$(am__mv) src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Namco.Tpo src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Namco.Po
#	$(AM_V_CXX)source='src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Namco.cpp' object='src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Namco.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Namco.obj `if test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Namco.cpp'; then $(CYGPATH_W) 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Namco.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Namco.cpp'; fi`

src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Oscs.o: src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Oscs.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Oscs.o -MD -MP -MF src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Oscs.Tpo -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Oscs.o `test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Oscs.cpp' || echo '$(srcdir)/'`src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Oscs.cpp
	$(AM_V_at)$(am__mv) src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Oscs.Tpo src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Oscs.Po
#	$(AM_V_CXX)source='src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Oscs.cpp' object='src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Oscs.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Oscs.o `test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Oscs.cpp' || echo '$(srcdir)/'`src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Oscs.cpp

src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Oscs.obj: src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Oscs.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Oscs.obj -MD -MP -MF src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Oscs.Tpo -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Oscs.obj `if test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Oscs.cpp'; then $(CYGPATH_W) 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Oscs.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Oscs.cpp'; fi`
	$(AM_V_at)$(am__mv) src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Oscs.Tpo src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Oscs.Po
#	$(AM_V_CXX)source='src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Oscs.cpp' object='src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Oscs.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Oscs.obj `if test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Oscs.cpp'; then $(CYGPATH_W) 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Oscs.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Oscs.cpp'; fi`

src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Vrc6.o: src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Vrc6.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Vrc6.o -MD -MP -MF src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Vrc6.Tpo -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Vrc6.o `test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Vrc6.cpp' || echo '$(srcdir)/'`src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Vrc6.cpp
	$(AM_V_at)$(am__mv) src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Vrc6.Tpo src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Vrc6.Po
#	$(AM_V_CXX)source='src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Vrc6.cpp' object='src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Vrc6.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Vrc6.o `test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Vrc6.cpp' || echo '$(srcdir)/'`src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Vrc6.cpp

src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Vrc6.obj: src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Vrc6.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Vrc6.obj -MD -MP -MF src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Vrc6.Tpo -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Vrc6.obj `if test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Vrc6.cpp'; then $(CYGPATH_W) 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Vrc6.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Vrc6.cpp'; fi`
	$(AM_V_at)$(am__mv) src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Vrc6.Tpo src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Vrc6.Po
#	$(AM_V_CXX)source='src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Vrc6.cpp' object='src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Vrc6.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nes_Vrc6.obj `if test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Vrc6.cpp'; then $(CYGPATH_W) 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Vrc6.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Nes_Snd_Emu-0.1.7/nes_apu/Nes_Vrc6.cpp'; fi`

src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nonlinear_Buffer.o: src/Nes_Snd_Emu-0.1.7/nes_apu/Nonlinear_Buffer.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nonlinear_Buffer.o -MD -MP -MF src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nonlinear_Buffer.Tpo -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nonlinear_Buffer.o `test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nonlinear_Buffer.cpp' || echo '$(srcdir)/'`src/Nes_Snd_Emu-0.1.7/nes_apu/Nonlinear_Buffer.cpp
	$(AM_V_at)$(am__mv) src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nonlinear_Buffer.Tpo src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nonlinear_Buffer.Po
#	$(AM_V_CXX)source='src/Nes_Snd_Emu-0.1.7/nes_apu/Nonlinear_Buffer.cpp' object='src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nonlinear_Buffer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nonlinear_Buffer.o `test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nonlinear_Buffer.cpp' || echo '$(srcdir)/'`src/Nes_Snd_Emu-0.1.7/nes_apu/Nonlinear_Buffer.cpp

src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nonlinear_Buffer.obj: src/Nes_Snd_Emu-0.1.7/nes_apu/Nonlinear_Buffer.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -MT src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nonlinear_Buffer.obj -MD -MP -MF src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nonlinear_Buffer.Tpo -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nonlinear_Buffer.obj `if test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nonlinear_Buffer.cpp'; then $(CYGPATH_W) 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nonlinear_Buffer.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Nes_Snd_Emu-0.1.7/nes_apu/Nonlinear_Buffer.cpp'; fi`
	$(AM_V_at)$(am__mv) src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nonlinear_Buffer.Tpo src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nonlinear_Buffer.Po
#	$(AM_V_CXX)source='src/Nes_Snd_Emu-0.1.7/nes_apu/Nonlinear_Buffer.cpp' object='src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nonlinear_Buffer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mines_CXXFLAGS) $(CXXFLAGS) -c -o src/Nes_Snd_Emu-0.1.7/nes_apu/mines-Nonlinear_Buffer.obj `if test -f 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nonlinear_Buffer.cpp'; then $(CYGPATH_W) 'src/Nes_Snd_Emu-0.1.7/nes_apu/Nonlinear_Buffer.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Nes_Snd_Emu-0.1.7/nes_apu/Nonlinear_Buffer.cpp'; fi`

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) distdir-am

distdir-am: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f src/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/$(am__dirstamp)
	-rm -f src/Nes_Snd_Emu-0.1.7/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/Nes_Snd_Emu-0.1.7/$(am__dirstamp)
	-rm -f src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/Nes_Snd_Emu-0.1.7/nes_apu/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
		-rm -f src/$(DEPDIR)/mines-_nes_apu.Po
	-rm -f src/$(DEPDIR)/mines-display_window.Po
	-rm -f src/$(DEPDIR)/mines-gl_shader.Po
	-rm -f src/$(DEPDIR)/mines-ines_mapper.Po
	-rm -f src/$(DEPDIR)/mines-ines_mapper0.Po
	-rm -f src/$(DEPDIR)/mines-ines_mapper1.Po
	-rm -f src/$(DEPDIR)/mines-ines_mapper2.Po
	-rm -f src/$(DEPDIR)/mines-ines_mapper3.Po
	-rm -f src/$(DEPDIR)/mines-ines_mapper7.Po
	-rm -f src/$(DEPDIR)/mines-main.Po
	-rm -f src/$(DEPDIR)/mines-mines_sys.Po
	-rm -f src/$(DEPDIR)/mines-nes_cart.Po
	-rm -f src/$(DEPDIR)/mines-nes_controllers.Po
	-rm -f src/$(DEPDIR)/mines-nes_cpu.Po
	-rm -f src/$(DEPDIR)/mines-nes_ppu.Po
	-rm -f src/Nes_Snd_Emu-0.1.7/$(DEPDIR)/mines-Sound_Queue.Po
	-rm -f src/Nes_Snd_Emu-0.1.7/$(DEPDIR)/mines-Wave_Writer.Po
	-rm -f src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Blip_Buffer.Po
	-rm -f src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Multi_Buffer.Po
	-rm -f src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Apu.Po
	-rm -f src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Namco.Po
	-rm -f src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Oscs.Po
	-rm -f src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Vrc6.Po
	-rm -f src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nonlinear_Buffer.Po
	-rm -f src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-apu_snapshot.Po
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
		-rm -f src/$(DEPDIR)/mines-_nes_apu.Po
	-rm -f src/$(DEPDIR)/mines-display_window.Po
	-rm -f src/$(DEPDIR)/mines-gl_shader.Po
	-rm -f src/$(DEPDIR)/mines-ines_mapper.Po
	-rm -f src/$(DEPDIR)/mines-ines_mapper0.Po
	-rm -f src/$(DEPDIR)/mines-ines_mapper1.Po
	-rm -f src/$(DEPDIR)/mines-ines_mapper2.Po
	-rm -f src/$(DEPDIR)/mines-ines_mapper3.Po
	-rm -f src/$(DEPDIR)/mines-ines_mapper7.Po
	-rm -f src/$(DEPDIR)/mines-main.Po
	-rm -f src/$(DEPDIR)/mines-mines_sys.Po
	-rm -f src/$(DEPDIR)/mines-nes_cart.Po
	-rm -f src/$(DEPDIR)/mines-nes_controllers.Po
	-rm -f src/$(DEPDIR)/mines-nes_cpu.Po
	-rm -f src/$(DEPDIR)/mines-nes_ppu.Po
	-rm -f src/Nes_Snd_Emu-0.1.7/$(DEPDIR)/mines-Sound_Queue.Po
	-rm -f src/Nes_Snd_Emu-0.1.7/$(DEPDIR)/mines-Wave_Writer.Po
	-rm -f src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Blip_Buffer.Po
	-rm -f src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Multi_Buffer.Po
	-rm -f src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Apu.Po
	-rm -f src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Namco.Po
	-rm -f src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Oscs.Po
	-rm -f src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nes_Vrc6.Po
	-rm -f src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-Nonlinear_Buffer.Po
	-rm -f src/Nes_Snd_Emu-0.1.7/nes_apu/$(DEPDIR)/mines-apu_snapshot.Po
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--depfiles am--refresh check \
	check-am clean clean-binPROGRAMS clean-cscope clean-generic \
	cscope cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-binPROGRAMS install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am install-man \
	install-pdf install-pdf-am install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic pdf pdf-am ps ps-am \
	tags tags-am uninstall uninstall-am uninstall-binPROGRAMS

.PRECIOUS: Makefile


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
